### ISSUE TITLE
您好，我使用python3 display.py出错

### ISSUE THREAD

**Issue by 17702513221** [friedhelm739/Insightface-tensorflow#1]
File "/home/xs/Insightface-tensorflow/core/ResNet_v2.py", line 206
    ]gitput_stride,
                 ^
SyntaxError: invalid syntax
报错如上，请问该怎么改

**Comment by friedhelm739** [comment]
我上传代码时可能碰到键盘了， 按照下面resnet_v2_101的格式
  return resnet_v2(inputs, blocks, num_classes, is_training=is_training,
                   global_pool=global_pool, output_stride=output_stride,
                   include_root_block=True, spatial_squeeze=spatial_squeeze,
                   reuse=reuse, scope=scope)
复制过来覆盖就好了
